apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: vaibhav-pvc
  namespace: vaibhav-ns

spec:
  storageClassName: vaibhav-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
