apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: vaibhav-pvc2
  namespace: vaibhav-ns

spec:
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
