apiVersion: v1
kind: Pod

metadata:
  name: gemini-nginx-pod
  namespace: gemini-pro
  labels:
    project: gemini

spec:
  containers:
  - image: nginx
    name: multi-container-pod
    ports:
    - containerPort: 80
  - image: linuxserver/firefox
    name: firefox-container
    ports:
    - containerPort: 3000
    # volumeMounts:
    # - mountPath: /var/dhondu/
    #   name: gemini-vol
