apiVersion: v1
kind: Pod

metadata:
  name: gemini-firefox-pod
  namespace: gemini-pro
  labels:
    project: gemini

spec:
  containers:
  - image: linuxserver/firefox
    name: firefox-container01
    ports:
    - containerPort: 300
    # volumeMounts:
    # - mountPath: /var/dhondu/
    #   name: gemini-vol
