apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistenet-volume-claim
  namespace: gemini-ns

spec:
  storageClassName: taxi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  # selector:
    # matchLabels:
    #   papa: dhondu
