apiVersion: apps/v1
kind: Deployment

metadata:
  name : dhondu-deployment
  namespace: default
spec:
  replicas : 5
  selector :
    matchExpressions	:
    - key	: nginx
      operator	: In 
      values	: 
      - dhondu
  template:
    metadata:
      name : nginx-dpod
      namespace	: vaibhav-ns
      labels:
        nginx : dhondu
    spec:
      containers:
      - image : nginx:stable-perl
        name : nginx-container
        ports :
        - containerPort : 80